sonar.projectKey=plugin.video.hdrezka.tv
sonar.projectName=plugin.video.hdrezka.tv
sonar.sources=.
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=__pycache__/**,*.pyc
sonar.test.inclusions=tests/**
